spring:
  datasource:
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cache
    password: gc14,xyk

mybatis:
  configuration:
    map-underscore-to-camel-case: true
