spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/mall?characterEncoding=UTF-8&useUnicode=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: gc14,xyk

#mybatis 日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
